### ISSUE TITLE
Problem with VPAID 1.1

### ISSUE THREAD

**Issue by JudithDu** [MailOnline/VPAIDFLASHClient#1]
Hi!
All is correctly working with a 2.0 VPAID but I need to play a 1.1 VPAID and the ad doesn't play.
It seems that the functions are correctly called (the callbacks are called) but I receive no events (neither AdError/AdLog neither AdLoaded after calling the initAd method).
Here is the uri of my vpaid : http://rtr.innovid.com/r1.559698c32385d5.56352662;cb=1597048868

Thank's.

**Comment by Fetz** [comment]
Hi @JudithDu, in theory should work with 1.1 VPAID because we only found vpaid 1.1 ad's.
see our demo page using videojs http://mailonline.github.io/videojs-vast-vpaid/

But with that ad and another we got from innovid we are not getting AdStarted event. Using flash debugger no error is throw...

I will try to contact them to get more details from their side.

**Comment by Fetz** [comment]
Hey @JudithDu I fixed the issue with the ad with this commit 08440aea59c9258e3b4304365dd7e89abd8ea418, the ad was not liking much the bulkloader I was using to load the ad. So I remove the dependency

**Comment by JudithDu** [comment]
Thank's for the fix !
