### ISSUE TITLE
Ignore aspect ratio on resizeAd

### ISSUE THREAD

**Issue by theifish** [MailOnline/VPAIDFLASHClient#12]
Now it respects aspect ratio when set width and height with resizeAd (height priority), and it's not possible to fit creative into player's viewport.
Maybe the solution of the issue is to add param to ignore aspect ratio for creatives.

**Comment by Fetz** [comment]
resizeAd is doing 2 resizes, one resizing the flash that is loading the ad, and then forwarding the resize to the ad. Since the ad resize is not controlled by us [and we are following the specification](http://www.iab.com/wp-content/uploads/2015/06/VPAID_2_0_Final_04-10-2012.pdf)

3.1.3 resizeAd()
resizeAd(width : Number, height : Number, viewMode : String) : void

we don't have any way to force the ad to ignore the aspect ratio
