### ISSUE TITLE
Wrong call to vpaid properties

### ISSUE THREAD

**Issue by JudithDu** [MailOnline/VPAIDFLASHClient#2]
Hi!

I've seen a problem in your VPAIDAdUnit.js file. In the methods getAdLinear, getAdWidth, getAdHeight, getAdExpanded, getAdSkippableState, getAdRemainingTime, getAdCompanions and getAdIcons. The corresponding vpaid properties are written without the "get" prefix.
And the same in your VPAIDWrapper.as file. You want to call properties and not methods so you have to remove the parenthesis when you call it (eg: public function get adWidth():Number{return ad.adWidth;})

Thank's

**Comment by Fetz** [comment]
Hello @JudithDu yes you are right, but because we want that the [VPAIDFlash](https://github.com/MailOnline/VPAIDFLASHClient) and [VPAIDHTML5](https://github.com/MailOnline/VPAIDHTML5Client) to have almost the same API, so we decided to follow the javascript implementation instead the the flash implementation [see spec](http://www.iab.net/media/file/VPAID_2.0_Final_04-10-2012.pdf) page 51 (implementation of vpaid js) the getter's and setters are prefix with get and set.

example copied from the pdf
```javascript
VPAIDWrapper.prototype.getAdExpanded = function() {
   console.log("getAdExpanded");
   return this._creative.getAdExpanded();
};
```

they probably implemented like this because getters and setters is only supported in new browsers

- [get](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get)
- [ \_\_defineGetter\_\_ ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/__defineGetter__)
- [defineProperty](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty)

even if they are prefixed with get/set, in the [flash side they are mapped to use the getter and setter without the prefix](https://github.com/MailOnline/VPAIDFLASHClient/blame/master/flash/src/com/dailymail/vpaid/VPAIDFlash.as#L141)

There was some issues with the mapping I fixed with the commit bced6d3.
